<a href="https://colab.research.google.com/github/cbermudez13/eel4815_final_coding_assignment/blob/main/group_1_problem_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
## two columns cannot be equal, a column cannot be all +1 or all -1
## a similar example was in lecture
import numpy as np
from numpy import mean
from numpy import std
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn import datasets
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OutputCodeClassifier

iris_dataset = datasets.load_iris()
X = iris_dataset.data
Y = iris_dataset.target

print("The number of all datapoints is ", len(X))

print("The number of features per datapoint is ", len(X[0]))

X_train,X_test = X[0:100],X[100:]
Y_train,Y_test = Y[0:100],Y[100:]


print("The number of training datapoints is ", len(X_train))
print("The number of testing  datapoints is ", len(X_test))
#print(X.target_names)


The number of all datapoints is  150
The number of features per datapoint is  4
The number of training datapoints is  100
The number of testing  datapoints is  50


In [11]:
C1 = np.array([[1, -1, -1, 1], [-1, 1, -1, 1], [-1, -1, 1, -1]])
print(C1)
print("\n")
C2 = np.array([[1, -1, -1, 1], [1, 1, -1, 1], [-1, -1, 1, -1]])
print(C2)


[[ 1 -1 -1  1]
 [-1  1 -1  1]
 [-1 -1  1 -1]]


[[ 1 -1 -1  1]
 [ 1  1 -1  1]
 [-1 -1  1 -1]]


In [13]:
classification_model = make_pipeline(StandardScaler(), SVC(kernel="linear", verbose = True))
##need to update

classification_model.fit(X_train,Y_train)
#ecoc = OutputCodeClassifier(model, code_size=2, random_state=1)
#print(X.shape,Y.shape)

[LibSVM]

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(kernel='linear', verbose=True))])

In [18]:
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# evaluate the model and collect the scores
#n_iris = cross_val_score(ecoc, X, Y, scoring='accuracy', cv=cv, n_jobs=-1)
# summarize the performance
#print('Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

In [ ]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OutputCodeClassifier
# define dataset
X, y = make_classification(n_samples=150, n_features=2, n_informative=0, n_redundant=0, random_state=1, n_classes=3)
# define the binary classification model
model = LogisticRegression()
# define the ecoc model
ecoc = OutputCodeClassifier(model, code_size=2, random_state=1)
# fit the model on the whole dataset
ecoc.fit(X, y)
# make a single prediction
row = [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
yhat = ecoc.predict(row)
print('Predicted Class: %d' % yhat[0])

In [ ]:
# Next, lets test the data by computing the testing dataset classification accuracy

CA_cnt = 0
for test_data_point_index in range(len(X_test)):
  test_data_point = X_test[test_data_point_index]
  # obtain the predicted label:
  predicted_label = classification_model.predict([test_data_point])
  # compare the predicted label with the true test label 
  true_label = Y_test[test_data_point_index]
  if predicted_label == true_label:
    CA_cnt = CA_cnt + 1
  
  # logger:
  #print("Testing poing index {}. [Predicted label, True label] = [{},{}]".format(test_data_point_index,predicted_label,true_label))

print("The classification accuracy of the test dataset is {}%".format(100*CA_cnt/len(X_test)))


The Matrix C3 cannot be used as it possesses a column of just -1. Furthermore, it may also be important to note than it possesses a row of eniterly -1 as well. These features will reduce the uniqueness of the encoded label/matrix. 