<a href="https://colab.research.google.com/github/cbermudez13/eel4815_final_coding_assignment/blob/main/group_1_problem_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# eigen values are needed here
# we have a similar example regarding PCA with the code specifying the use of only numpy
import numpy as np
np.random.seed(seed=1111)
# In this code, we show how to use PCA...
# Generate some dataset... 

number_of_data_points = 20
number_of_features_per_data_point = 8

# stack the data into some list
data = np.zeros(shape=(number_of_data_points,number_of_features_per_data_point))
for data_index in range(number_of_data_points):
  data_point = np.random.normal(loc=(0,0), scale = 0.1,   size=(number_of_features_per_data_point,2)) 
  data_point = np.random.uniform(low = -1, high = 1, size=(number_of_features_per_data_point))
  print("datapoint {} = ".format(data_index),data_point)
  data[data_index,:] = data_point

datapoint 0 =  [ 0.27829033  0.27474913  0.22174859  0.8600371   0.63299983  0.53884985
 -0.82919815  0.33000546]
datapoint 1 =  [-0.36961352  0.05105697  0.29169876  0.50129095 -0.88794542  0.74841174
 -0.29252993  0.60886138]
datapoint 2 =  [-0.90045225 -0.02007737  0.01436786 -0.24514244 -0.56103477  0.52872486
  0.20571251  0.39759014]
datapoint 3 =  [-0.21251461 -0.24130074 -0.01148743  0.66185076 -0.76515153 -0.68163008
  0.15700348 -0.44708878]
datapoint 4 =  [-0.42702955  0.23633954 -0.48257607 -0.75109729  0.77145566  0.49831414
  0.03404134 -0.75171658]
datapoint 5 =  [-0.19707532 -0.90754503 -0.14391801  0.46785546  0.68663869 -0.20283691
  0.63587754 -0.83093676]
datapoint 6 =  [-0.57319652  0.1050368  -0.33181649 -0.27484692  0.3100581   0.39557794
  0.20901428  0.92593281]
datapoint 7 =  [-0.99689456  0.13580354 -0.70581406 -0.13221598  0.69676654 -0.74657357
  0.16037686 -0.33393912]
datapoint 8 =  [-0.26862693  0.41014699  0.9590418  -0.22670193  0.03145369  0.76785701


In [3]:
X_bar = np.mean(data,axis=0)
print("X bar = ", X_bar)
print("X bar is of size {}, which is equal to the number of features for each data point, {}".format((X_bar.shape),number_of_features_per_data_point))

X bar =  [-0.08338448 -0.02253193  0.03884116  0.03060223 -0.06169549  0.2299217
  0.00794119  0.09258652]
X bar is of size (8,), which is equal to the number of features for each data point, 8


In [4]:
print("The covariance of the data is size {} X {}.".format(number_of_data_points,number_of_data_points))
# For each row in the data matrix, we subtract the datapoint vector with the mean vector X_bar and save it in a data matrix

data_matrix_minus_mean = np.zeros(shape=(number_of_data_points,number_of_features_per_data_point))
for data_index in range(number_of_data_points):
  data_matrix_minus_mean[data_index,:] = data[data_index,:] - X_bar
print(data_matrix_minus_mean)

The covariance of the data is size 20 X 20.
[[ 0.36167482  0.29728106  0.18290743  0.82943487  0.69469532  0.30892815
  -0.83713934  0.23741893]
 [-0.28622903  0.0735889   0.25285761  0.47068872 -0.82624993  0.51849004
  -0.30047112  0.51627485]
 [-0.81706777  0.00245456 -0.0244733  -0.27574467 -0.49933928  0.29880316
   0.19777132  0.30500362]
 [-0.12913013 -0.21876881 -0.05032858  0.63124853 -0.70345604 -0.91155178
   0.14906229 -0.53967531]
 [-0.34364507  0.25887148 -0.52141723 -0.78169952  0.83315115  0.26839244
   0.02610014 -0.8443031 ]
 [-0.11369083 -0.88501309 -0.18275916  0.43725323  0.74833418 -0.43275862
   0.62793634 -0.92352328]
 [-0.48981204  0.12756873 -0.37065764 -0.30544915  0.37175359  0.16565624
   0.20107309  0.83334629]
 [-0.91351007  0.15833547 -0.74465522 -0.16281821  0.75846203 -0.97649527
   0.15243566 -0.42652565]
 [-0.18524245  0.43267892  0.92020065 -0.25730416  0.09314918  0.53793531
   0.34543923 -0.22122222]
 [ 0.84770591  0.05685375  0.69477725 -0.612917

In [5]:
# Now, for each vector in data_matrix_minus_mean, we compute the outer product matrix 
matricies_list = []
for data_index in range(number_of_data_points):
  outer_product_matrix = np.outer(data_matrix_minus_mean[data_index,:],data_matrix_minus_mean[data_index,:])
  matricies_list.append(outer_product_matrix)

Covariance_matrix = np.array ( (1/number_of_data_points) * sum(matricies_list) )

print((Covariance_matrix))

[[ 0.3331067  -0.04843332  0.141523   -0.01640458 -0.00410445  0.09221445
  -0.04355394 -0.05558779]
 [-0.04843332  0.20468456 -0.01154686 -0.11568229 -0.00993335 -0.0568021
   0.01203501  0.13393241]
 [ 0.141523   -0.01154686  0.31993662  0.04393334  0.06761247  0.09798757
  -0.06594135 -0.00451158]
 [-0.01640458 -0.11568229  0.04393334  0.25850874  0.0393357   0.03460061
  -0.02476153 -0.04391112]
 [-0.00410445 -0.00993335  0.06761247  0.0393357   0.37162913  0.0162557
  -0.00756647 -0.08354368]
 [ 0.09221445 -0.0568021   0.09798757  0.03460061  0.0162557   0.29129558
  -0.00546358  0.02431322]
 [-0.04355394  0.01203501 -0.06594135 -0.02476153 -0.00756647 -0.00546358
   0.29772082 -0.06356306]
 [-0.05558779  0.13393241 -0.00451158 -0.04391112 -0.08354368  0.02431322
  -0.06356306  0.32180553]]


In [6]:
# Next, we get the highest eigenvalues and eigenvectors to construct the PCA weights matrix

number_of_reduced_features = 1

eig_values, eig_vectors = np.linalg.eig(Covariance_matrix)
print("eig_values = ", eig_values)
print("eig_vectors = ", eig_vectors)


eig_values =  [0.61803132 0.47013    0.05959477 0.12726081 0.18347523 0.35592351
 0.26949377 0.31477827]
eig_vectors =  [[-0.48652509  0.28566653  0.05088499  0.58517918  0.10676088 -0.31552012
   0.29186064  0.37487406]
 [ 0.30145723  0.28643548  0.7666657   0.04952476 -0.17408062  0.31434286
  -0.02740756  0.32708192]
 [-0.51106336  0.30981087 -0.1539445  -0.39590058 -0.64672689  0.18565412
  -0.0207514   0.09613296]
 [-0.25415095 -0.22796079  0.35710454  0.42512708 -0.35034731 -0.02058397
  -0.1757551  -0.64894353]
 [-0.31491517 -0.36770012 -0.11328138  0.21604044  0.22458055  0.77643123
  -0.09187922  0.21070177]
 [-0.36600317  0.24200253  0.22765561 -0.24037435  0.47351472 -0.13867199
  -0.67274268 -0.04290368]
 [ 0.1568519  -0.35359235 -0.14431442  0.20986976 -0.37545669 -0.27516649
  -0.57502506  0.48801621]
 [ 0.29817112  0.6079509  -0.41584307  0.41127085 -0.04097312  0.26258807
  -0.30177374 -0.19422109]]


In [7]:
# Given the above eigen values and vector, we get the following W_PCA matrix

W_PCA = np.zeros(shape=(number_of_reduced_features, number_of_features_per_data_point))

# we pick the highest two values and their corresponding eigrn values
W_PCA[0,:] = eig_vectors[0,:]

print("The PCA matrix = \n", W_PCA)

The PCA matrix = 
 [[-0.48652509  0.28566653  0.05088499  0.58517918  0.10676088 -0.31552012
   0.29186064  0.37487406]]


In [8]:
# Next, for each data point, we get the reduced vector z...

reduced_data = np.zeros(shape=(number_of_data_points,1))

for data_index in range(number_of_data_points):
  reduced_data[data_index,:] = np.matmul(W_PCA, data[data_index,:])

print("The reduced matrix = ", reduced_data)

The reduced matrix =  [[ 0.23691271]
 [ 0.31453119]
 [ 0.27200175]
 [ 0.4327798 ]
 [-0.53553806]
 [ 0.11447912]
 [ 0.44756132]
 [ 0.64209233]
 [-0.02000207]
 [-0.64188854]
 [-0.14844456]
 [ 0.1358179 ]
 [-0.68227216]
 [-0.03232675]
 [ 0.31396465]
 [-0.15155876]
 [-0.84889982]
 [-0.85762618]
 [ 1.47646632]
 [-0.22983696]]


In [9]:
# Next, we get the highest eigenvalues and eigenvectors to construct the PCA weights matrix

number_of_reduced_features = 2

eig_values, eig_vectors = np.linalg.eig(Covariance_matrix)
print("eig_values = ", eig_values)
print("eig_vectors = ", eig_vectors)


eig_values =  [0.61803132 0.47013    0.05959477 0.12726081 0.18347523 0.35592351
 0.26949377 0.31477827]
eig_vectors =  [[-0.48652509  0.28566653  0.05088499  0.58517918  0.10676088 -0.31552012
   0.29186064  0.37487406]
 [ 0.30145723  0.28643548  0.7666657   0.04952476 -0.17408062  0.31434286
  -0.02740756  0.32708192]
 [-0.51106336  0.30981087 -0.1539445  -0.39590058 -0.64672689  0.18565412
  -0.0207514   0.09613296]
 [-0.25415095 -0.22796079  0.35710454  0.42512708 -0.35034731 -0.02058397
  -0.1757551  -0.64894353]
 [-0.31491517 -0.36770012 -0.11328138  0.21604044  0.22458055  0.77643123
  -0.09187922  0.21070177]
 [-0.36600317  0.24200253  0.22765561 -0.24037435  0.47351472 -0.13867199
  -0.67274268 -0.04290368]
 [ 0.1568519  -0.35359235 -0.14431442  0.20986976 -0.37545669 -0.27516649
  -0.57502506  0.48801621]
 [ 0.29817112  0.6079509  -0.41584307  0.41127085 -0.04097312  0.26258807
  -0.30177374 -0.19422109]]


In [10]:
# Given the above eigen values and vector, we get the following W_PCA matrix

W_PCA = np.zeros(shape=(number_of_reduced_features, number_of_features_per_data_point))

# we pick the highest two values and their corresponding eigrn values
W_PCA[0,:] = eig_vectors[0,:]
W_PCA[1,:] = eig_vectors[1,:]

print("The PCA matrix = \n", W_PCA)

The PCA matrix = 
 [[-0.48652509  0.28566653  0.05088499  0.58517918  0.10676088 -0.31552012
   0.29186064  0.37487406]
 [ 0.30145723  0.28643548  0.7666657   0.04952476 -0.17408062  0.31434286
  -0.02740756  0.32708192]]


In [11]:
# Next, for each data point, we get the reduced vector z...

reduced_data = np.zeros(shape=(number_of_data_points,2))

for data_index in range(number_of_data_points):
  reduced_data[data_index,:] = np.matmul(W_PCA, data[data_index,:])

print("The reduced matrix = ", reduced_data)

The reduced matrix =  [[ 0.23691271  0.56504641]
 [ 0.31453119  0.74866067]
 [ 0.27200175  0.10994865]
 [ 0.4327798  -0.34081541]
 [-0.53553806 -0.69266743]
 [ 0.11447912 -0.87903251]
 [ 0.44756132 -0.04321272]
 [ 0.64209233 -1.27888813]
 [-0.02000207  0.9446734 ]
 [-0.64188854  0.93291945]
 [-0.14844456 -0.33527467]
 [ 0.1358179   0.50484037]
 [-0.68227216  0.71711488]
 [-0.03232675 -0.18096948]
 [ 0.31396465 -0.15116803]
 [-0.15155876  0.53952993]
 [-0.84889982  0.69346977]
 [-0.85762618 -0.51576434]
 [ 1.47646632 -0.15661389]
 [-0.22983696  1.07386135]]


In [12]:
# Next, we get the highest eigenvalues and eigenvectors to construct the PCA weights matrix

number_of_reduced_features = 3

eig_values, eig_vectors = np.linalg.eig(Covariance_matrix)
print("eig_values = ", eig_values)
print("eig_vectors = ", eig_vectors)


eig_values =  [0.61803132 0.47013    0.05959477 0.12726081 0.18347523 0.35592351
 0.26949377 0.31477827]
eig_vectors =  [[-0.48652509  0.28566653  0.05088499  0.58517918  0.10676088 -0.31552012
   0.29186064  0.37487406]
 [ 0.30145723  0.28643548  0.7666657   0.04952476 -0.17408062  0.31434286
  -0.02740756  0.32708192]
 [-0.51106336  0.30981087 -0.1539445  -0.39590058 -0.64672689  0.18565412
  -0.0207514   0.09613296]
 [-0.25415095 -0.22796079  0.35710454  0.42512708 -0.35034731 -0.02058397
  -0.1757551  -0.64894353]
 [-0.31491517 -0.36770012 -0.11328138  0.21604044  0.22458055  0.77643123
  -0.09187922  0.21070177]
 [-0.36600317  0.24200253  0.22765561 -0.24037435  0.47351472 -0.13867199
  -0.67274268 -0.04290368]
 [ 0.1568519  -0.35359235 -0.14431442  0.20986976 -0.37545669 -0.27516649
  -0.57502506  0.48801621]
 [ 0.29817112  0.6079509  -0.41584307  0.41127085 -0.04097312  0.26258807
  -0.30177374 -0.19422109]]


In [13]:
# Given the above eigen values and vector, we get the following W_PCA matrix

W_PCA = np.zeros(shape=(number_of_reduced_features, number_of_features_per_data_point))

# we pick the highest two values and their corresponding eigrn values
W_PCA[0,:] = eig_vectors[0,:]
W_PCA[1,:] = eig_vectors[2,:]
W_PCA[2,:] = eig_vectors[5,:]

print("The PCA matrix = \n", W_PCA)

The PCA matrix = 
 [[-0.48652509  0.28566653  0.05088499  0.58517918  0.10676088 -0.31552012
   0.29186064  0.37487406]
 [-0.51106336  0.30981087 -0.1539445  -0.39590058 -0.64672689  0.18565412
  -0.0207514   0.09613296]
 [-0.36600317  0.24200253  0.22765561 -0.24037435  0.47351472 -0.13867199
  -0.67274268 -0.04290368]]


In [14]:
# Next, for each data point, we get the reduced vector z...

reduced_data = np.zeros(shape=(number_of_data_points,3))

for data_index in range(number_of_data_points):
  reduced_data[data_index,:] = np.matmul(W_PCA, data[data_index,:])

print("The reduced matrix = ", reduced_data)

The reduced matrix =  [[ 0.23691271 -0.69213678  0.57707619]
 [ 0.31453119  0.73915309 -0.26001898]
 [ 0.27200175  1.04375706 -0.10752073]
 [ 0.4327798   0.0956508  -0.4965502 ]
 [-0.53553806  0.1837313   0.58971605]
 [ 0.11447912 -0.91831918 -0.33159258]
 [ 0.44756132  0.44296775  0.13735993]
 [ 0.64209233  0.08789754  0.60872308]
 [-0.02000207  0.3089802   0.14659787]
 [-0.64188854  0.24911932 -0.69961808]
 [-0.14844456  0.83964393  0.1340112 ]
 [ 0.1358179  -0.86419433 -0.46138699]
 [-0.68227216 -0.27842292  0.91713431]
 [-0.03232675  0.05504956  0.08423951]
 [ 0.31396465  1.10275323 -0.1921512 ]
 [-0.15155876  0.84166364 -0.31987446]
 [-0.84889982 -0.80779625  0.20385072]
 [-0.85762618  0.1482047  -1.64373481]
 [ 1.47646632  0.46971886  0.03490148]
 [-0.22983696 -0.87019826  0.20164799]]


The PCA matrices were constructed by first choosing the largest eigen values and their respective vectors. The matrix dimensions were defined by the number of features. The cases with features of 1 and 2, have the largest eigen values within the first two indices so those two were selected for each part respectively. The last case with 3 features shared the largest indices at 0, 1, but the next largest was found at index 5. The dimensionality of 2 was used in the first couple cases to ensure that the largest values were considered, while 3 features/dimensions was used for the third case to consider for all the possible largest values within their respective vectors. The reasoning followed with what was seen within the notes.